### ISSUE TITLE
 Exception while property mapping at property path "":It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property

### ISSUE THREAD

**Issue by falkoneven** [haassie/rh_recaptcha#4]
TYPO3          6.2.14
Powermail     2.10.0
rh_recaptcha 0.0.2

We receive this error after we confirm the data on the confirmation page. The form only contains:
- Naam
- Email
- reCaptcha
- submit

Does this error happen to others aswell ?

**Comment by haassie** [comment]
This is fixed now in the release of version 0.0.3

**Comment by pixelplant** [comment]
I'm still getting this now with the latest version of powermail in TYPO3 v8.7.1
Once I get on the confirmation page the info is displayed correctly, but if I refresh this page though, the same error is displayed.

_Exception while property mapping at property path "": It is not allowed to map property "answers". You need to use $propertyMappingConfiguration->allowProperties('answers') to enable mapping of this property._
